### ISSUE TITLE
Platform upgrade Riddles.io

### ISSUE THREAD

**Issue by CaneloDigital** [theaigames/next#4]
booking.riddles.io

I just uploaded, around 15/20 minutes ago, two new bots, they are both still in compiling queue.
I don't know if it's the platform upgrade...
I do think so, because yesterday it was much quicker.

Additionally:
OSX 10.11 & Firefox 50: the upload button for new bots simply does nothing.
I needed to change to Chrome to be able to upload a new bot...

Oh: and on both firefox & chrome: the reply button in the posts did no effect, so I was forced to comment it here in github

**Comment by nikovanmeurs** [comment]
I think it did something in chrome and firefox, but simply took a while. Your message was posted 10x on the discussion board ;)

The delay simply has to do with the fact that we're scheduling more matches per minute than yesterday and our available server capacity hasn't scaled up accordingly. I'm currently adding servers while writing this, so the task backlog should be resolved in a few hours.

**Comment by CaneloDigital** [comment]
ups sorry for that ;-) ... please feel free to delete the entries in the discussion board...

**Comment by mpricope** [comment]
hey guys,

first of all great idea and well ... I think you just got overwhelmed by your popularity :) ... cause it seems that right now you really need to be patient to use it :)

So beside everything working extremely slow (or not working at all sometimes) I just have a few suggestions related to the new UI:
- previous UI had a nice feature to see the performance of every version. This seems to be gone now. It would be nice to see at least the performance of the current active Bot. 
- accordingly there was a very useful link in the overview page to go to the matches that my bot played. Now to get there you need to pass through the Match Log with the filter all ... which so far doesn't work (probably due to load).

I don't know if you remove some of these stuff to increase performance. I imagine that since for me the site rarely works,  you are pretty much swamped and scrambling to keep things together :) 

Keep up the good work!

**Comment by mpricope** [comment]
Also for the front-end of the site. You might consider accepting a limited number of connections and just show "server busy" for the rest of the people. It sucks ...but it sucks anyway due to a bigger load you expected :) Now  you are wasting a lot of processor power because people just refresh and you are trying to actually compute their request.  If you just put some circuit breaker in front you will actually be able to serve more request overall.

This until you figure out how to scale the whole thing :)

**Comment by nikovanmeurs** [comment]
Capacity is definitely a problem at the moment, with the biggest bottleneck being the API. The API is built on top of Google App Engine, which seemed like a great idea when we started out because most of the ops work and the scalability is being taken care of by the platform. However, GAE now proves to be a problem because it does not give us enough control over resource allocation, resulting in subpar performance.

We're currently rewriting the parts of the API in order to move away from Google App Engine. If all goes well we'll be testing this internally somewhere next week.

**Comment by mpricope** [comment]
now is a pain to see my matches :) ... cause if I go to "Match Log" and then try to filter to my matches it hangs. So i need to sort through all the other matches to try to figure out which are my own. There are less than players with probably a few thousand users each. So this means you have around 200-300k , maybe 1M matches to filter. Not that small ... but not that huge either.  I am wondering how you store those if this operation is basically doesn't work for me.

**Comment by nikovanmeurs** [comment]
@mpricope We're working on the issue right now, it should be fixed soon.

**edit**: The Match Log filter is fixed.

**Comment by mpricope** [comment]
cool. But now they seems to be sorted the other way around inside a page (only when you go for MyMatches)

**Comment by nikovanmeurs** [comment]
Fixed.
